<?php
/** @var \PHP10E2\LoyaltyPoints\Block\Info $block */
?>

<h2>You have <b><?= $block->getLoyaltyPoints() ?></b> Loyalty Points</h2>
<hr>
<h3>How to earn loyalty points</h3>
<p>After your friends follow your link and buy something from the store, you will receive <b><?= $block->getDataFromAdmin()?>%</b> of their order to your Loyalty Points Balance</p>
<div>
    <a href="<?= $block->getReferralLink() ?>">
        <?= $block->getReferralLink() ?>
    </a>
</div>